### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by anujpflash** [WesternPine/TicketBot#12]
Can you upload a prebuild .jar file, i am unable to build the app
I m getting these problems
and there is no resource folder

Description	Resource	Path	Location	Type
The method getAbr() is undefined for the type SupportType	Ticket.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports	line 163	Java Problem
The method getCommand(String, Guild, User) in the type CommandExecutor is not applicable for the arguments ()	CommandExecutor.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command	line 51	Java Problem
The method getCommand(String, Guild, User) in the type CommandExecutor is not applicable for the arguments ()	CommandExecutor.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command	line 52	Java Problem
The method getCommand(String, Guild, User) in the type CommandExecutor is not applicable for the arguments ()	CommandExecutor.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command	line 53	Java Problem
The method getCommand(String, Guild, User) in the type CommandExecutor is not applicable for the arguments ()	CommandExecutor.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command	line 59	Java Problem
The method getCommand(String, Guild, User) in the type CommandExecutor is not applicable for the arguments ()	CommandExecutor.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command	line 78	Java Problem
The method getIdentifier() is undefined for the type CommandExecutor	CommandExecutor.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command	line 49	Java Problem
The method getInstance() is undefined for the type TicketBot	Add.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command/commands	line 79	Java Problem
The method getInstance() is undefined for the type TicketBot	Ban.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getInstance() is undefined for the type TicketBot	Billing.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getInstance() is undefined for the type TicketBot	Blacklist.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command/commands	line 76	Java Problem
The method getInstance() is undefined for the type TicketBot	Bug.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getInstance() is undefined for the type TicketBot	Help.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command/commands	line 58	Java Problem
The method getInstance() is undefined for the type TicketBot	Help.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command/commands	line 59	Java Problem
The method getInstance() is undefined for the type TicketBot	Help.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command/commands	line 62	Java Problem
The method getInstance() is undefined for the type TicketBot	Help.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command/commands	line 63	Java Problem
The method getInstance() is undefined for the type TicketBot	Help.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command/commands	line 78	Java Problem
The method getInstance() is undefined for the type TicketBot	Help.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command/commands	line 79	Java Problem
The method getInstance() is undefined for the type TicketBot	Help.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command/commands	line 80	Java Problem
The method getInstance() is undefined for the type TicketBot	Help.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command/commands	line 81	Java Problem
The method getInstance() is undefined for the type TicketBot	Question.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getInstance() is undefined for the type TicketBot	Remove.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command/commands	line 79	Java Problem
The method getInstance() is undefined for the type TicketBot	Request.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getInstance() is undefined for the type TicketBot	ServerTable.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/sql	line 61	Java Problem
The method getInstance() is undefined for the type TicketBot	Suggest.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getInstance() is undefined for the type TicketBot	Support.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getInstance() is undefined for the type TicketBot	SupportType.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports	line 78	Java Problem
The method getInstance() is undefined for the type TicketBot	Ticket.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports	line 78	Java Problem
The method getInstance() is undefined for the type TicketBot	Ticket.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports	line 84	Java Problem
The method getInstance() is undefined for the type TicketBot	Ticket.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports	line 101	Java Problem
The method getInstance() is undefined for the type TicketBot	Ticket.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getInstance() is undefined for the type TicketBot	TicketBot.java	/TicketBot/src/main/java/dev/westernpine/ticketbot	line 67	Java Problem
The method getInstance() is undefined for the type TicketBot	TicketListener.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/events	line 19	Java Problem
The method getSetLoader() is undefined for the type Config.ConfigType	Config.java	/TicketBot/src/main/java/dev/westernpine/common/config	line 259	Java Problem
The method getString() is undefined for the type SupportType	Ban.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getString() is undefined for the type SupportType	Billing.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getString() is undefined for the type SupportType	Bug.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getString() is undefined for the type SupportType	Help.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command/commands	line 66	Java Problem
The method getString() is undefined for the type SupportType	Question.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getString() is undefined for the type SupportType	Request.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getString() is undefined for the type SupportType	Suggest.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getString() is undefined for the type SupportType	Support.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getString() is undefined for the type SupportType	SupportType.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports	line 59	Java Problem
The method getString() is undefined for the type SupportType	Ticket.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports/types	line 17	Java Problem
The method getSupportType() is undefined for the type SupportType	Help.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/command/commands	line 84	Java Problem
The method getSupportType() is undefined for the type SupportType	Ticket.java	/TicketBot/src/main/java/dev/westernpine/ticketbot/supports	line 99	Java Problem
The method getVariables() is undefined for the type TicketConfig	TicketBot.java	/TicketBot/src/main/java/dev/westernpine/ticketbot	line 45	Java Problem
The method getVariables() is undefined for the type TicketConfig	TicketBot.java	/TicketBot/src/main/java/dev/westernpine/ticketbot	line 46	Java Problem
The method getVariables() is undefined for the type TicketConfig	TicketBot.java	/TicketBot/src/main/java/dev/westernpine/ticketbot	line 52	Java Problem
The method getVariables() is undefined for the type TicketConfig	TicketBot.java	/TicketBot/src/main/java/dev/westernpine/ticketbot	line 71	Java Problem

**Comment by WesternPine** [comment]
My apologies. I meant to archive this repository, as it is no longer supported or being worked on. :(

I will write up a release later, and make sure it's in working condition before posting it. Check back a little later please :)

Again, this project is no longer supported. Anything you do from here out, any problems you encounter, any features you want to add, etc. will not be considered.

**Comment by WesternPine** [comment]
Release pushed and tested. Good luck!
